### ISSUE TITLE
USER STORY: Front page poll

### ISSUE THREAD

**Issue by MEdw4rds** [MEdw4rds/love-running#3]
In order to **share my opinion** as a **user**, I can **select my answer from a poll**

## Acceptance Criteria 

- Users can select from multiple choice 
- Between 3-6 options 
- Users can choose only one

## Tasks

- [ ] Create a form
- [ ] Create either checkbox or radio button poll 
- [ ] design form layout
- [ ] make sure users can only submit once
