### ISSUE TITLE
USER STORY: create post 

### ISSUE THREAD

**Issue by MEdw4rds** [MEdw4rds/love-running#5]
In order to **communicate with other site users** as a **user**, I can **create a post on a page**

## Acceptance Criteria 
- create user posts 
- have others be able to view posts

## Tasks
- [ ] create forum page
- [ ] create a way for users to post posts
- [ ] create a way for users to check their own posts
