### ISSUE TITLE
USER STORY: Comment on others posts

### ISSUE THREAD

**Issue by MEdw4rds** [MEdw4rds/love-running#6]
In order to **Interact with others in the community** as a **user**, I can **comment on others post**

## Acceptance Criteria 
- reply to user posts
- view users post

## Tasks
- [ ] be able to view others posts
- [ ] add the ability to edit their messages
- [ ] have the original poster be able to see the replies
